apiVersion: apps/v1
kind: Deployment
metadata:
  name: safebootstrap
  labels:
    app: safebootstrap
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: safebootstrap
  template:
    metadata:
      labels:
        app: safebootstrap
    spec:
      containers:
        - name: safebootstrap
          image: 'gcr.io/beaming-botany-293512/read-demo:latest'
          ports:
            - containerPort: 8090
