apiVersion: apps/v1
kind: Deployment
metadata:
  name: safebootstrap
  labels:
    app: safebootstrap
spec:
  replicas: 7
  selector:
    matchLabels:
      app: safebootstrap
  template:
    metadata:
      labels:
        app: safebootstrap
    spec:
      containers:
        - name: safebootstrap
          image: safebootstrap:v1
          ports:
            - containerPort: 8090
          volumeMounts:
            - name: safe-secret-volume
              mountPath: "/dev/shm/securityAssets/safe/"
              readOnly: true
          env:
            - name: ENV_NAME
              value: gouravba02lx.corp.amdocs.com
      volumes:
        - name: safe-secret-volume
          secret:
            secretName: safe-secret