apiVersion: apps/v1
kind: Deployment
metadata:
  name: safebootstrap
  labels:
    app: safebootstrap
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: safebootstrap
  template:
    metadata:
      labels:
        app: safebootstrap
    spec:
      containers:
        - name: safebootstrap
          image: 'gcr.io/beaming-botany-293512/read-demo:v1'
          ports:
            - containerPort: 8090
          volumeMounts:
            - name: safe-secret-volume
              mountPath: "/dev/shm/securityAssets/safe/"
          env:
          - name: ENV_NAME
            value: gouravba02lx.corp.amdocs.com
      volumes:
        - name: safe-secret-volume
          secret:
            secretName: safe-secret
